### ISSUE TITLE
support for http/https

### ISSUE THREAD

**Issue by dasturge** [facebookresearch/pytorchvideo#141]
## 🚀 Feature

opencv-python, decord, and pyav all support reading mp4s directly from an http/https address, from what I can see the implementations of their EncodedVideo subclasses do as well, I confirmed this with PyAV:

```
video = EncodedVideoPyAV(
    "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
    decode_audio=False,
)
vals = video.get_clip(1.0, 2.0)  # returns a tensor as expected
```

However, the iopath package doesn't recognize http/https addresses and therefore EncodedVideo/LabeledVideoDataset don't operate with urls (they actually fail silently if passed a url).

My use case is for model deployment where videos are accessible via https.  Downloading them to disk first is slower.

**Comment by kalyanvasudev** [comment]
We don't have plans to replace iopath since it makes it easy to be compatible different filesystems we work with. 

I presume you want this feature of loading videos from url for the inference stage? If so, all our EnodedVideo decoders also support passing binary raw video files. For your use case, you can easily download videos from url into raw binary objects using off the shelf python library like [`requests`](https://www.tutorialspoint.com/downloading-files-from-web-using-python)
