### ISSUE TITLE
How to get multi-clips from a video?

### ISSUE THREAD

**Issue by zhang-jr** [facebookresearch/pytorchvideo#55]
Currently, it seems that we can only get a single clip from a video at each iteration.

**Comment by kalyanvasudev** [comment]
You can change the ClipSampler - https://github.com/facebookresearch/pytorchvideo/blob/master/pytorchvideo/data/clip_sampling.py
in the dataloader to get mutliple clips from the same video. 
In case of random clip sampler, we sample only 1 clip from each video in each epoch. Whereas if you change to uniform clip sampler, we sampler multiple clips from the same video in the same epoch. 

Furthermore, you can also pass in your own custom clip sampler (built on our clip sampler abstraction) into the dataloader.

Please feel free to re-open the issue if the problem is not resolved.

**Comment by anisaha1** [comment]
Hi @kalyanvasudev, while using Pytorch DDP, what are the differences between these three scenarios?
1. Pass video_sampler=DistributedSampler as dataset argument and also pass sampler=DistributedSampler to dataloader
2. Pass video_sampler=DistributedSampler as dataset argument only
3. pass sampler=DistributedSampler to dataloader only
